services:
#    accb.example:
#        class: AcbbBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    acbb.image_uploader:
            class: AcbbBundle\ImageUpload
            arguments: ['%images_user_directory%']