admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_addteam:
    path:     /addteam
    defaults: { _controller: AdminBundle:Team:addteam }

admin_addmatch:
    path:     /addmatch
    defaults: { _controller: AdminBundle:Match:addmatch }

admin_adduser:
    path:     /adduser
    defaults: { _controller: AdminBundle:User:adduser }

admin_addclub:
    path:     /addclub
    defaults: { _controller: AdminBundle:Club:addclub }

admin_addmember:
    path:     /addmember
    defaults: { _controller: AdminBundle:Membership:addmember }

admin_addmedia:
    path:     /addmedia
    defaults: { _controller: AdminBundle:Media:addmedia }