services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    admin.image_uploader:
            class: AdminBundle\ImageUpload
            arguments: ['%images_directory%']