AcbbBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AcbbBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        placeBirth:
            type: string
            length: '45'
            column: place_birth
        job:
            type: string
            length: '45'
    lifecycleCallbacks: {  }
